feat: TwoSum completed, provided WriteUps for each problem
XavierCruz5106/Blind75 pull request #1
Opened 2024-10-24 19:09 UTC by XavierCruz5106

2024-10-24 19:21 UTC, anthonydmays requested changes

2024-10-24 19:21 UTC, anthonydmays commented on TwoSum/README.md
> +## Nested Loop
Link to the problem on LeetCode so viewers can find the context.

2024-10-24 19:21 UTC, anthonydmays commented on TwoSum/README.md
> +After implementing the last 2 solutions I wondered if i can leverage a data structure to reduce my time complexity. I figured since a lookup in a hashmap is constant time i should be able to store an
HashMap lookup is not constant time.

2024-10-24 19:21 UTC, anthonydmays commented on TwoSum/app/src/main/java/twosum/App.java
> +    public static int[] twoSumMap(int[] nums, int target) {
You're missing a minor optimization to this code. In fact, you're missing it in all the methods. There's only one valid solution right?

2024-10-24 19:21 UTC, anthonydmays commented on TwoSum/app/src/main/java/twosum/App.java
> +        Map<Integer, Integer> map = new HashMap<>();
See if you can come up with a better, more descriptive variable name.

2024-10-24 19:21 UTC, anthonydmays commented on TwoSum/app/src/test/java/twosum/AppTest.java
> +    @Test void appHasAGreeting() {
Why even have a test if you're not going to use it? Make it useful by actually adding test cases or just delete.

Also, wire it up to GitHub actions so that you can show the tests passed.

2024-10-24 19:21 UTC, anthonydmays commented on TwoSum/README.md
> +```java
Instead of duplicating here, try using code references straight from the file. Just a nice touch but totally unnecessary. https://www.stevemar.net/github-code-in-readme/

2024-10-24 19:21 UTC, anthonydmays commented on TwoSum/app/src/main/java/twosum/App.java
> +    public static void main(String[] args) {
Your test code should just be tests.

2024-10-24 19:24 UTC, XavierCruz5106 commented on TwoSum/README.md
> +## Nested Loop
Thanks

2024-10-24 19:29 UTC, XavierCruz5106 commented on TwoSum/README.md
> +After implementing the last 2 solutions I wondered if i can leverage a data structure to reduce my time complexity. I figured since a lookup in a hashmap is constant time i should be able to store an
Apologies i found many conflicting answers. Based on the bigocheatsheet it should be O(n) time. Fixed the mistake

2024-10-24 19:33 UTC, XavierCruz5106 commented on TwoSum/app/src/main/java/twosum/App.java
> +    public static int[] twoSumMap(int[] nums, int target) {
I believe i saw where you are going with this. I have commit a new change which i believe is an optimization please confirm when you get the opportunity!

2024-10-24 19:38 UTC, XavierCruz5106 commented on TwoSum/app/src/main/java/twosum/App.java
> +        Map<Integer, Integer> map = new HashMap<>();
Changed to `indexMap`, Thanks!

2024-10-24 19:39 UTC, XavierCruz5106 commented on TwoSum/app/src/test/java/twosum/AppTest.java
> +    @Test void appHasAGreeting() {
Will implement tests

2024-10-24 19:40 UTC, XavierCruz5106 commented on TwoSum/README.md
> +```java
Thanks, ill check this out

2024-10-24 22:56 UTC, XavierCruz5106 commented on TwoSum/app/src/test/java/twosum/AppTest.java
> +    @Test void appHasAGreeting() {
Wired up to GH Actions!

2024-10-25 04:44 UTC, anthonydmays approved these changes

2024-10-25 04:44 UTC, merged